//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCANBs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atracao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Atracao()
        {
            this.Apresentador = new HashSet<Apresentador>();
        }
    
        public short IdAtracao { get; set; }
        public short IdEvento { get; set; }
        public string ImagemAtracao { get; set; }
        public string NomeAtracao { get; set; }
    
        public virtual Evento Evento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apresentador> Apresentador { get; set; }
    }
}
