//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCANBs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evento()
        {
            this.Atracao = new HashSet<Atracao>();
            this.IngressoApresentador = new HashSet<IngressoApresentador>();
            this.IngressoEspectador = new HashSet<IngressoEspectador>();
            this.OrganizadorEvento = new HashSet<OrganizadorEvento>();
        }
    
        public short IdEvento { get; set; }
        public string NomeEvento { get; set; }
        public System.DateTime DataInicio { get; set; }
        public System.DateTime DataFinal { get; set; }
        public string ImagemEvento { get; set; }
        public Nullable<decimal> ValorSugestivoApresentador { get; set; }
        public Nullable<decimal> ValorSugestivoEspectador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atracao> Atracao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngressoApresentador> IngressoApresentador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngressoEspectador> IngressoEspectador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizadorEvento> OrganizadorEvento { get; set; }
    }
}
