//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCANBs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngressoEspectador
    {
        public short IdIngressoEspectador { get; set; }
        public short IdEvento { get; set; }
        public short IdPessoaEspectador { get; set; }
        public short IdPagamento { get; set; }
    
        public virtual Espectador Espectador { get; set; }
        public virtual Evento Evento { get; set; }
        public virtual Pagamento Pagamento { get; set; }
    }
}
