//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCANBs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizadorEvento
    {
        public short IdPessoaOrganizador { get; set; }
        public short IdEvento { get; set; }
        public System.DateTime DataInicioVinculo { get; set; }
        public Nullable<System.DateTime> DataFimVinculo { get; set; }
        public Nullable<short> IdPessoaFuncionarioVinculo { get; set; }
        public Nullable<short> IdPessoaFuncionarioDesvinculo { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public virtual Funcionario Funcionario1 { get; set; }
        public virtual Organizador Organizador { get; set; }
    }
}
