//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCANBs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pagamento()
        {
            this.IngressoApresentador = new HashSet<IngressoApresentador>();
            this.IngressoEspectador = new HashSet<IngressoEspectador>();
        }
    
        public short IdPagamento { get; set; }
        public decimal ValorTotal { get; set; }
        public Nullable<decimal> Desconto { get; set; }
        public short IdSituacaoPagamento { get; set; }
        public System.DateTime DataPagamento { get; set; }
        public short IdPessoaFuncionario { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngressoApresentador> IngressoApresentador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngressoEspectador> IngressoEspectador { get; set; }
        public virtual SituacaoPagamento SituacaoPagamento { get; set; }
    }
}
