//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCANBs.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCANBsEntities : DbContext
    {
        public SCANBsEntities()
            : base("name=SCANBsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apresentador> Apresentador { get; set; }
        public virtual DbSet<Atracao> Atracao { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Espectador> Espectador { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Funcionario> Funcionario { get; set; }
        public virtual DbSet<IngressoApresentador> IngressoApresentador { get; set; }
        public virtual DbSet<IngressoEspectador> IngressoEspectador { get; set; }
        public virtual DbSet<Organizador> Organizador { get; set; }
        public virtual DbSet<OrganizadorEvento> OrganizadorEvento { get; set; }
        public virtual DbSet<Pagamento> Pagamento { get; set; }
        public virtual DbSet<Pessoa> Pessoa { get; set; }
        public virtual DbSet<SituacaoPagamento> SituacaoPagamento { get; set; }
        public virtual DbSet<Telefone> Telefone { get; set; }
        public virtual DbSet<Veiculo> Veiculo { get; set; }
    }
}
