//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCANBs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefone
    {
        public short IdTelefone { get; set; }
        public int NumeroTelefone { get; set; }
        public short IdPessoa { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Pessoa Pessoa1 { get; set; }
    }
}
