//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCANBs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculo
    {
        public short IdVeiculo { get; set; }
        public string FotoVeiculo { get; set; }
        public short IdPessoaApresentador { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public short Ano { get; set; }
        public string Placa { get; set; }
    
        public virtual Apresentador Apresentador { get; set; }
        public virtual Apresentador Apresentador1 { get; set; }
    }
}
